title: USTC LUG
description: 中国科学技术大学 Linux 用户协会是由中国科学技术大学在校的 GNU/Linux 爱好者发起并组成的团体，旨在联合科大的 GNU/Linux 使用者，搭建信息交流共享的平台，宣传自由软件的价值，提高自由软件社区文化氛围，推广自由软件的应用。
url: https://news.ustclug.org/

paginate: 7
paginate_path: /page:num/

excerpt_separator: <!--more-->

permalink: /:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-paginate
